export const externalSuites = [
  {
    id: "elm-review",
    repo: "https://github.com/jfmengels/elm-review.git",
    branch: "main",
    description: "Primary elm-review package test suite",
    tags: ["starter", "elm-review"],
    timeoutSecs: 600,
  },
  {
    id: "elm-review-common",
    repo: "https://github.com/jfmengels/elm-review-common.git",
    branch: "main",
    description: "Common elm-review rule package",
    tags: ["starter", "elm-review-rule"],
    timeoutSecs: 300,
  },
  {
    id: "elm-review-unused",
    repo: "https://github.com/jfmengels/elm-review-unused.git",
    branch: "main",
    description: "Unused-code elm-review rules",
    tags: ["starter", "elm-review-rule"],
    timeoutSecs: 300,
  },
  {
    id: "elm-review-simplify",
    repo: "https://github.com/jfmengels/elm-review-simplify.git",
    branch: "main",
    description: "Large simplification-focused elm-review rule suite",
    tags: ["starter", "elm-review-rule"],
    timeoutSecs: 600,
  },
  {
    id: "elm-markdown",
    repo: "https://github.com/dillonkearns/elm-markdown.git",
    branch: "master",
    description: "Real-world markdown parser package test suite",
    tags: ["real-project", "parser-heavy"],
    timeoutSecs: 120,
    cases: [
      {
        id: "full-suite",
        description: "Auto-discovered full suite",
        timeoutSecs: 120,
      },
      {
        id: "helpers",
        description: "Small targeted helper regression file",
        globs: ["tests/HelpersTests.elm"],
        timeoutSecs: 60,
      },
      {
        id: "aggregate",
        description: "Larger parser-focused aggregate file",
        globs: ["tests/Tests.elm"],
        timeoutSecs: 120,
      },
    ],
  },
];
