module MutationTestRunner exposing (run)

{-| Mutation testing runner that uses the elm-interpreter.

For each mutation generated by `Mutator`, this swaps the mutated source
into the in-memory source list and re-evaluates the test suite via the
interpreter. No files are written to disk — everything is in memory.

A mutation is "killed" if any test fails (good — test suite caught it).
A mutation "survives" if all tests still pass (bad — test suite has a gap).

-}

import Ansi.Color
import BackendTask exposing (BackendTask)
import BackendTask.Do as Do
import BackendTask.Extra
import BackendTask.File as File
import Cli.Option as Option
import Cli.OptionsParser as OptionsParser
import Cli.Program as Program
import Elm.Syntax.Expression exposing (Expression(..))
import Eval.Module
import FatalError exposing (FatalError)
import Mutator exposing (Mutation)
import Pages.Script as Script exposing (Script)
import Path exposing (Path)
import ProjectSources
import Types


type alias Config =
    { mutateFile : String
    , testFile : String
    }


programConfig : Program.Config Config
programConfig =
    Program.config
        |> Program.add
            (OptionsParser.build Config
                |> OptionsParser.with
                    (Option.optionalKeywordArg "mutate"
                        |> Option.map (Maybe.withDefault "src/MathLib.elm")
                        |> Option.withDescription "The source file to mutate"
                    )
                |> OptionsParser.with
                    (Option.optionalKeywordArg "test"
                        |> Option.map (Maybe.withDefault "src/MathLibTests.elm")
                        |> Option.withDescription "The test file that exercises the mutated code"
                    )
            )


run : Script
run =
    Script.withCliOptions programConfig task


task : Config -> BackendTask FatalError ()
task config =
    BackendTask.Extra.profiling "mutation-test-runner" <|
        Do.log (Ansi.Color.fontColor Ansi.Color.brightBlue "Loading project sources for mutation testing") <| \_ ->
        Do.do
            (BackendTask.Extra.timed "Loading sources" "Loaded sources"
                (ProjectSources.loadProjectSources
                    { projectDir = Path.path "."
                    , userSourceDirectories = [ "src" ]
                    , targetFile = config.testFile
                    }
                    |> BackendTask.map (List.map patchSource)
                )
            )
        <| \allSources ->
        -- Read the source file we want to mutate
        Do.allowFatal (File.rawFile config.mutateFile) <| \mutateSource ->
        Do.log (Ansi.Color.fontColor Ansi.Color.brightBlue ("Generating mutations for " ++ config.mutateFile)) <| \_ ->
        let
            mutations : List Mutation
            mutations =
                Mutator.generateMutations mutateSource

            mutationCount : Int
            mutationCount =
                List.length mutations
        in
        Do.log ("Found " ++ String.fromInt mutationCount ++ " mutations") <| \_ ->
        Do.log (Ansi.Color.fontColor Ansi.Color.brightBlue "Running mutation tests via interpreter") <| \_ ->
        let
            results : List MutationResult
            results =
                mutations
                    |> List.map (runMutation allSources mutateSource)
        in
        displayMutationReport results


type MutationResult
    = Killed { mutation : Mutation, failCount : Int }
    | Survived { mutation : Mutation }
    | ErrorResult { mutation : Mutation, error : String }


runMutation : List String -> String -> Mutation -> MutationResult
runMutation allSources originalSource mutation =
    let
        -- Replace the original source with the mutated version in the source list
        mutatedSources : List String
        mutatedSources =
            allSources
                |> List.map
                    (\source ->
                        if source == originalSource then
                            mutation.mutatedSource

                        else
                            source
                    )

        -- Evaluate the test module's `results` value with mutated sources.
        -- The test module is last in the source list (loadProjectSources puts
        -- targetFile last), so `FunctionOrValue [] "results"` resolves to it.
        result : Result Types.Error Types.Value
        result =
            Eval.Module.evalProject
                mutatedSources
                (FunctionOrValue [] "results")
    in
    case result of
        Ok (Types.String output) ->
            -- Parse the simple test output format: "passCount,failCount,totalCount\n..."
            case String.split "," (String.lines output |> List.head |> Maybe.withDefault "") of
                [ _, failStr, _ ] ->
                    case String.toInt failStr of
                        Just failCount ->
                            if failCount > 0 then
                                Killed { mutation = mutation, failCount = failCount }

                            else
                                Survived { mutation = mutation }

                        Nothing ->
                            ErrorResult { mutation = mutation, error = "Could not parse fail count from: " ++ output }

                _ ->
                    ErrorResult { mutation = mutation, error = "Unexpected output format: " ++ output }

        Ok other ->
            ErrorResult { mutation = mutation, error = "Expected String result, got: " ++ Debug.toString other }

        Err (Types.ParsingError _) ->
            ErrorResult { mutation = mutation, error = "Parsing error in mutated source" }

        Err (Types.EvalError evalErr) ->
            ErrorResult { mutation = mutation, error = "Eval error: " ++ Debug.toString evalErr.error }


displayMutationReport : List MutationResult -> BackendTask FatalError ()
displayMutationReport results =
    let
        killed =
            List.filter isKilled results

        survived =
            List.filter isSurvived results

        errors =
            List.filter isError results

        total =
            List.length results

        score =
            if total == 0 then
                "N/A"

            else
                let
                    pct =
                        toFloat (List.length killed) / toFloat total * 100
                in
                String.fromInt (round pct) ++ "%"
    in
    Do.each killed
        (\r ->
            case r of
                Killed { mutation, failCount } ->
                    Script.log
                        (Ansi.Color.fontColor Ansi.Color.green
                            ("  ✓ Killed (" ++ String.fromInt failCount ++ " failed): " ++ mutation.description ++ " (line " ++ String.fromInt mutation.line ++ ")")
                        )

                _ ->
                    Script.log ""
        )
    <| \_ ->
    Do.each survived
        (\r ->
            case r of
                Survived { mutation } ->
                    Script.log
                        (Ansi.Color.fontColor Ansi.Color.red
                            ("  ✗ Survived: " ++ mutation.description ++ " (line " ++ String.fromInt mutation.line ++ ")")
                        )

                _ ->
                    Script.log ""
        )
    <| \_ ->
    Do.each errors
        (\r ->
            case r of
                ErrorResult { mutation, error } ->
                    Script.log
                        (Ansi.Color.fontColor Ansi.Color.yellow
                            ("  ? Error: " ++ mutation.description ++ " — " ++ error)
                        )

                _ ->
                    Script.log ""
        )
    <| \_ ->
    let
        summaryColor =
            if List.isEmpty survived then
                Ansi.Color.fontColor Ansi.Color.brightGreen

            else
                Ansi.Color.fontColor Ansi.Color.brightRed
    in
    Do.log
        (summaryColor
            ("\nMutation Score: "
                ++ score
                ++ " ("
                ++ String.fromInt (List.length killed)
                ++ " killed, "
                ++ String.fromInt (List.length survived)
                ++ " survived, "
                ++ String.fromInt (List.length errors)
                ++ " errors, "
                ++ String.fromInt total
                ++ " total)"
            )
        )
    <| \_ ->
    Do.noop


isKilled : MutationResult -> Bool
isKilled r =
    case r of
        Killed _ ->
            True

        _ ->
            False


isSurvived : MutationResult -> Bool
isSurvived r =
    case r of
        Survived _ ->
            True

        _ ->
            False


isError : MutationResult -> Bool
isError r =
    case r of
        ErrorResult _ ->
            True

        _ ->
            False


{-| Patch Test framework kernel code for interpreter compatibility.
-}
patchSource : String -> String
patchSource source =
    if String.contains "runThunk =\n    Elm.Kernel.Test.runThunk" source then
        source
            |> String.replace
                "runThunk =\n    Elm.Kernel.Test.runThunk"
                "runThunk fn =\n    Ok (fn ())"

    else
        source
