module MutationTestRunner exposing (run)

{-| Mutation testing runner that uses the elm-interpreter.

For each mutation generated by `Mutator`, this swaps the mutated source
into the in-memory source list and re-evaluates the test suite via the
interpreter. No files are written to disk — everything is in memory.

A mutation is "killed" if any test fails (good — test suite caught it).
A mutation "survives" if all tests still pass (bad — test suite has a gap).

The test module just needs to expose `suite : Test` — the standard elm-test
convention. The runner auto-generates the wrapper to evaluate it.

Performance: sources are parsed once into a ProjectEnv via buildProjectEnv.
Each mutation only re-parses the single mutated module via evalWithEnv.

-}

import Ansi.Color
import BackendTask exposing (BackendTask)
import BackendTask.Do as Do
import BackendTask.Extra
import BackendTask.File as File
import BackendTask.Time
import Cli.Option as Option
import Cli.OptionsParser as OptionsParser
import Cli.Program as Program
import DepGraph
import Elm.Syntax.Expression exposing (Expression(..))
import Eval.Module
import TestAnalysis
import FatalError exposing (FatalError)
import Mutator exposing (Mutation)
import Pages.Script as Script exposing (Script)
import Path exposing (Path)
import ProjectSources
import Set
import Time
import Types


type alias Config =
    { mutateFile : String
    , testFile : String
    , suiteName : String
    , sourceDirs : List String
    }


programConfig : Program.Config Config
programConfig =
    Program.config
        |> Program.add
            (OptionsParser.build Config
                |> OptionsParser.with
                    (Option.optionalKeywordArg "mutate"
                        |> Option.map (Maybe.withDefault "src/MathLib.elm")
                        |> Option.withDescription "The source file to mutate"
                    )
                |> OptionsParser.with
                    (Option.optionalKeywordArg "test"
                        |> Option.map (Maybe.withDefault "src/MathLibTests.elm")
                        |> Option.withDescription "The test file (must expose suite : Test)"
                    )
                |> OptionsParser.with
                    (Option.optionalKeywordArg "suite"
                        |> Option.map (Maybe.withDefault "suite")
                        |> Option.withDescription "The name of the test value (default: suite)"
                    )
                |> OptionsParser.with
                    (Option.optionalKeywordArg "source-dirs"
                        |> Option.map (Maybe.map (String.split ",") >> Maybe.withDefault [])
                        |> Option.withDescription "Extra source directories (comma-separated)"
                    )
            )


run : Script
run =
    Script.withCliOptions programConfig task


task : Config -> BackendTask FatalError ()
task config =
    BackendTask.Extra.profiling "mutation-test-runner" <|
        Do.log (Ansi.Color.fontColor Ansi.Color.brightBlue "Loading project sources for mutation testing") <| \_ ->
        Do.allowFatal (File.rawFile config.testFile) <| \testSource ->
        let
            testModuleName : String
            testModuleName =
                DepGraph.parseModuleName testSource
                    |> Maybe.withDefault "Tests"

            candidateNames : List String
            candidateNames =
                TestAnalysis.getCandidateNames testSource
        in
        Do.log ("Found " ++ String.fromInt (List.length candidateNames) ++ " candidate values in " ++ testModuleName) <| \_ ->
        Do.do
            (BackendTask.Extra.timed "Loading sources" "Loaded sources"
                (ProjectSources.loadProjectSources
                    { projectDir = Path.path "."
                    , userSourceDirectories = "src" :: config.sourceDirs
                    , targetFile = config.testFile
                    , skipPackages = kernelPackages
                    }
                    |> BackendTask.map
                        (\sources ->
                            List.map patchSource sources ++ [ simpleTestRunnerSource ]
                        )
                )
            )
        <| \allSources ->
        Do.log ("Loaded " ++ String.fromInt (List.length allSources) ++ " source files") <| \_ ->
        -- Build the project environment once (expensive parse phase)
        Do.do
            (BackendTask.Extra.timed "Building project env" "Built project env"
                (case Eval.Module.buildProjectEnv allSources of
                    Ok env ->
                        BackendTask.succeed env

                    Err (Types.ParsingError _) ->
                        BackendTask.fail (FatalError.fromString "Failed to parse sources")

                    Err (Types.EvalError _) ->
                        BackendTask.fail (FatalError.fromString "Failed to build env")
                )
            )
        <| \projectEnv ->
        -- Discover which candidates are actually Test values via the interpreter
        Do.do
            (BackendTask.Extra.timed "Discovering test values" "Discovered test values"
                (let
                    probeResults =
                        candidateNames
                            |> List.map
                                (\name ->
                                    ( name, TestAnalysis.probeCandidate projectEnv testModuleName name )
                                )

                    testValues =
                        probeResults
                            |> List.filterMap
                                (\( name, result ) ->
                                    case result of
                                        Ok _ ->
                                            Just name

                                        Err _ ->
                                            Nothing
                                )

                    rejections =
                        probeResults
                            |> List.filterMap
                                (\( name, result ) ->
                                    case result of
                                        Err reason ->
                                            Just (testModuleName ++ "." ++ name ++ ": " ++ reason)

                                        Ok _ ->
                                            Nothing
                                )
                 in
                 if List.isEmpty testValues then
                    BackendTask.fail
                        (FatalError.fromString
                            ("No Test values found in "
                                ++ testModuleName
                                ++ ".\nCandidates rejected:\n  "
                                ++ String.join "\n  " rejections
                            )
                        )

                 else
                    (if List.isEmpty rejections then
                        BackendTask.succeed ()

                     else
                        Script.log ("Rejected candidates: " ++ String.join ", " rejections)
                    )
                        |> BackendTask.map (\() -> testValues)
                )
            )
        <| \testValues ->
        let
            wrapperSource : String
            wrapperSource =
                generateTestWrapper testModuleName testValues
        in
        Do.log ("Discovered test values: " ++ String.join ", " (List.map (\v -> testModuleName ++ "." ++ v) testValues)) <| \_ ->
        Do.allowFatal (File.rawFile config.mutateFile) <| \mutateSource ->
        Do.log (Ansi.Color.fontColor Ansi.Color.brightBlue ("Generating mutations for " ++ config.mutateFile)) <| \_ ->
        let
            mutations : List Mutation
            mutations =
                Mutator.generateMutations mutateSource

            mutationCount : Int
            mutationCount =
                List.length mutations
        in
        Do.log ("Found " ++ String.fromInt mutationCount ++ " mutations") <| \_ ->
        Do.log (Ansi.Color.fontColor Ansi.Color.brightBlue "Running mutation tests via interpreter") <| \_ ->
        Do.do BackendTask.Time.now <| \startTime ->
        let
            results : List MutationResult
            results =
                mutations
                    |> List.map (runMutation projectEnv wrapperSource)
        in
        Do.do BackendTask.Time.now <| \endTime ->
        let
            evalMs =
                Time.posixToMillis endTime - Time.posixToMillis startTime

            perMutation =
                if mutationCount > 0 then
                    evalMs // mutationCount

                else
                    0
        in
        Do.log
            ("Evaluated "
                ++ String.fromInt mutationCount
                ++ " mutations in "
                ++ String.fromInt evalMs
                ++ "ms ("
                ++ String.fromInt perMutation
                ++ "ms/mutation)"
            )
        <| \_ ->
        displayMutationReport results


{-| Generate a wrapper module that bridges SimpleTestRunner and the user's test module.

The user's test module just needs `suite : Test`. This wrapper calls
`SimpleTestRunner.runToString` on it so the interpreter can evaluate it
as a String.

-}
generateTestWrapper : String -> List String -> String
generateTestWrapper testModuleName testValues =
    let
        suiteExpr =
            case testValues of
                [ single ] ->
                    testModuleName ++ "." ++ single

                multiple ->
                    "Test.describe \"" ++ testModuleName ++ "\" [" ++ String.join ", " (List.map (\v -> testModuleName ++ "." ++ v) multiple) ++ "]"
    in
    String.join "\n"
        [ "module MutationTestWrapper__ exposing (wrapperResult__)"
        , ""
        , "import SimpleTestRunner"
        , "import Test"
        , "import " ++ testModuleName
        , ""
        , "wrapperResult__ : String"
        , "wrapperResult__ ="
        , "    SimpleTestRunner.runToString (" ++ suiteExpr ++ ")"
        , ""
        ]


type MutationResult
    = Killed { mutation : Mutation, failCount : Int }
    | Survived { mutation : Mutation }
    | ErrorResult { mutation : Mutation, error : String }


{-| Run a single mutation using the pre-built ProjectEnv.

Only the mutated module source is re-parsed — the rest of the environment
is reused. The wrapper module is passed as the last additional source so
its imports are used for expression resolution.

-}
runMutation : Eval.Module.ProjectEnv -> String -> Mutation -> MutationResult
runMutation projectEnv wrapperSource mutation =
    let
        -- Pass mutated source + wrapper as additional sources.
        -- The mutated source overrides the original module in the env.
        -- The wrapper is last so its imports resolve the expression.
        result : Result Types.Error Types.Value
        result =
            Eval.Module.evalWithEnv
                projectEnv
                [ mutation.mutatedSource, wrapperSource ]
                (FunctionOrValue [] "wrapperResult__")
    in
    case result of
        Ok (Types.String output) ->
            case String.split "," (String.lines output |> List.head |> Maybe.withDefault "") of
                [ _, failStr, _ ] ->
                    case String.toInt failStr of
                        Just failCount ->
                            if failCount > 0 then
                                Killed { mutation = mutation, failCount = failCount }

                            else
                                Survived { mutation = mutation }

                        Nothing ->
                            ErrorResult { mutation = mutation, error = "Could not parse fail count from: " ++ output }

                _ ->
                    ErrorResult { mutation = mutation, error = "Unexpected output format: " ++ output }

        Ok other ->
            ErrorResult { mutation = mutation, error = "Expected String result, got: " ++ "(unexpected value type)" }

        Err (Types.ParsingError _) ->
            ErrorResult { mutation = mutation, error = "Parsing error in mutated source" }

        Err (Types.EvalError evalErr) ->
            ErrorResult { mutation = mutation, error = "Eval error" }


displayMutationReport : List MutationResult -> BackendTask FatalError ()
displayMutationReport results =
    let
        killed =
            List.filter isKilled results

        survived =
            List.filter isSurvived results

        errors =
            List.filter isError results

        total =
            List.length results

        score =
            if total == 0 then
                "N/A"

            else
                let
                    pct =
                        toFloat (List.length killed) / toFloat total * 100
                in
                String.fromInt (round pct) ++ "%"
    in
    Do.each killed
        (\r ->
            case r of
                Killed { mutation, failCount } ->
                    Script.log
                        (Ansi.Color.fontColor Ansi.Color.green
                            ("  ✓ Killed (" ++ String.fromInt failCount ++ " failed): " ++ mutation.description ++ " (line " ++ String.fromInt mutation.line ++ ")")
                        )

                _ ->
                    Script.log ""
        )
    <| \_ ->
    Do.each survived
        (\r ->
            case r of
                Survived { mutation } ->
                    Script.log
                        (Ansi.Color.fontColor Ansi.Color.red
                            ("  ✗ Survived: " ++ mutation.description ++ " (line " ++ String.fromInt mutation.line ++ ")")
                        )

                _ ->
                    Script.log ""
        )
    <| \_ ->
    Do.each errors
        (\r ->
            case r of
                ErrorResult { mutation, error } ->
                    Script.log
                        (Ansi.Color.fontColor Ansi.Color.yellow
                            ("  ? Error: " ++ mutation.description ++ " — " ++ error)
                        )

                _ ->
                    Script.log ""
        )
    <| \_ ->
    let
        summaryColor =
            if List.isEmpty survived then
                Ansi.Color.fontColor Ansi.Color.brightGreen

            else
                Ansi.Color.fontColor Ansi.Color.brightRed
    in
    Do.log
        (summaryColor
            ("\nMutation Score: "
                ++ score
                ++ " ("
                ++ String.fromInt (List.length killed)
                ++ " killed, "
                ++ String.fromInt (List.length survived)
                ++ " survived, "
                ++ String.fromInt (List.length errors)
                ++ " errors, "
                ++ String.fromInt total
                ++ " total)"
            )
        )
    <| \_ ->
    Do.noop


isKilled : MutationResult -> Bool
isKilled r =
    case r of
        Killed _ ->
            True

        _ ->
            False


isSurvived : MutationResult -> Bool
isSurvived r =
    case r of
        Survived _ ->
            True

        _ ->
            False


isError : MutationResult -> Bool
isError r =
    case r of
        ErrorResult _ ->
            True

        _ ->
            False



{-| The SimpleTestRunner module source, embedded so it's available regardless
of what project directory the tool runs from.
-}
simpleTestRunnerSource : String
simpleTestRunnerSource =
    String.join "\n"
        [ "module SimpleTestRunner exposing (runToString)"
        , "import Expect"
        , "import Random"
        , "import Test exposing (Test)"
        , "import Test.Runner"
        , "runToString suite ="
        , "    let"
        , "        runners = case Test.Runner.fromTest 1 (Random.initialSeed 42) suite of"
        , "            Test.Runner.Plain list -> Ok list"
        , "            Test.Runner.Only list -> Ok list"
        , "            Test.Runner.Skipping list -> Ok list"
        , "            Test.Runner.Invalid msg -> Err msg"
        , "    in"
        , "    case runners of"
        , "        Err msg -> \"0,1,1\\nFAIL:Invalid test suite: \" ++ msg"
        , "        Ok runnerList ->"
        , "            let"
        , "                results = List.map runOneRunner runnerList"
        , "                passCount = List.length (List.filter .passed results)"
        , "                failCount = List.length results - passCount"
        , "                formatResult r = if r.passed then \"PASS:\" ++ r.label else \"FAIL:\" ++ r.label ++ \" | \" ++ r.message"
        , "            in"
        , "            String.fromInt passCount ++ \",\" ++ String.fromInt failCount ++ \",\" ++ String.fromInt (List.length results) ++ \"\\n\" ++ (List.map formatResult results |> String.join \"\\n\")"
        , "runOneRunner runner ="
        , "    let"
        , "        labelPath = List.reverse runner.labels |> String.join \" > \""
        , "        expectations = runner.run ()"
        , "        failures = expectations |> List.filterMap (\\expectation -> Test.Runner.getFailureReason expectation |> Maybe.map .description)"
        , "        passed = List.isEmpty failures"
        , "    in"
        , "    { passed = passed, label = labelPath, message = if passed then \"\" else String.join \"; \" failures }"
        ]


{-| Packages with kernel/native JS code that the interpreter can't handle.
The interpreter has built-in implementations for elm/core.
-}
kernelPackages : Set.Set String
kernelPackages =
    Set.fromList
        [ "elm/json"
        , "elm/regex"
        , "elm/html"
        , "elm/virtual-dom"
        , "elm/bytes"
        , "elm/browser"
        , "elm/http"
        , "elm/file"
        , "elm/url"
        ]


{-| Patch Test framework kernel code for interpreter compatibility.
-}
patchSource : String -> String
patchSource source =
    if String.contains "runThunk =\n    Elm.Kernel.Test.runThunk" source then
        source
            |> String.replace
                "runThunk =\n    Elm.Kernel.Test.runThunk"
                "runThunk fn =\n    Ok (fn ())"

    else
        source
